import { describe, expect, it } from 'vitest';
import {
  ACTIVATION_CLICK_REUSE_MS,
  RuntimeInteractionTracker,
  createRuntimeInteractionId,
  groupRuntimeInteractions,
  runtimeInteractionTitle,
  shouldReuseClickInteraction,
} from '../lib/runtime/causality';
import type { RuntimeEvent } from '../shared/types';

function event(overrides: Partial<RuntimeEvent> & Pick<RuntimeEvent, 'id' | 'timestamp' | 'kind' | 'title'>): RuntimeEvent {
  return {
    severity: 'info',
    ...overrides,
  };
}

describe('runtime causality', () => {
  it('creates stable interaction ids for an epoch and sequence', () => {
    expect(createRuntimeInteractionId('page', 1)).toBe('ix-page-1');
    expect(createRuntimeInteractionId('page', 35)).toBe('ix-page-z');
    expect(createRuntimeInteractionId('page', 36)).toBe('ix-page-10');
  });

  it('reuses click interactions only for the same pointer or keyboard activation target', () => {
    expect(
      shouldReuseClickInteraction({
        source: 'keyboard',
        activationKey: 'Enter',
        triggerSelector: '#save',
        clickSelector: '#save',
        elapsedMs: 100,
      }),
    ).toBe(true);

    expect(
      shouldReuseClickInteraction({
        source: 'keyboard',
        activationKey: 'Tab',
        triggerSelector: '#save',
        clickSelector: '#save',
        elapsedMs: 100,
      }),
    ).toBe(false);

    expect(
      shouldReuseClickInteraction({
        source: 'pointer',
        triggerSelector: '#save',
        clickSelector: '#cancel',
        elapsedMs: 50,
      }),
    ).toBe(false);

    expect(
      shouldReuseClickInteraction({
        source: 'pointer',
        triggerSelector: '#save',
        clickSelector: '#save',
        elapsedMs: ACTIVATION_CLICK_REUSE_MS + 1,
      }),
    ).toBe(false);
  });

  it('keeps causal events inside a bounded interaction window', () => {
    let now = 1000;
    const tracker = new RuntimeInteractionTracker('page', () => now);

    const interaction = tracker.begin('keyboard', '#save', 'Enter');
    now += 100;
    expect(tracker.current()).toBe(interaction);
    tracker.touch(interaction);

    now += 1601;
    expect(tracker.current()).toBeUndefined();
  });

  it('reuses the synthetic click generated by keyboard activation', () => {
    let now = 1000;
    const tracker = new RuntimeInteractionTracker('page', () => now);

    const keyInteraction = tracker.begin('keyboard', '#save', 'Enter');
    now += 50;
    expect(tracker.click('#save')).toBe(keyInteraction);

    now += 50;
    expect(tracker.click('#cancel')).not.toBe(keyInteraction);
  });

  it('groups correlated events and keeps ambient events isolated', () => {
    const events: RuntimeEvent[] = [
      event({ id: '1', timestamp: 10, kind: 'keydown', title: 'Key: Enter', interactionId: 'ix-a-1' }),
      event({
        id: '2',
        timestamp: 15,
        kind: 'dom-mutation',
        title: 'DOM removed',
        interactionId: 'ix-a-1',
      }),
      event({
        id: '3',
        timestamp: 20,
        kind: 'focus-lost',
        title: 'Focused element removed',
        interactionId: 'ix-a-1',
        outcome: 'review',
        causes: [
          {
            type: 'FOCUSED_NODE_REMOVED',
            confidence: 'deterministic',
            summary: 'Focused node was removed.',
          },
        ],
      }),
      event({ id: '4', timestamp: 30, kind: 'live-region', title: 'Live region updated' }),
    ];

    const groups = groupRuntimeInteractions(events);

    expect(groups).toHaveLength(2);
    expect(groups[0]).toMatchObject({
      id: 'ix-a-1',
      correlated: true,
      startedAt: 10,
      endedAt: 20,
      findings: 1,
    });
    expect(groups[0]?.events).toHaveLength(3);
    expect(groups[0]?.causes.map((cause) => cause.type)).toEqual(['FOCUSED_NODE_REMOVED']);

    expect(groups[1]).toMatchObject({
      id: 'ambient:4',
      correlated: false,
      findings: 0,
    });
  });

  it('deduplicates root causes inside the same interaction', () => {
    const rootCause = {
      type: 'FOCUS_FELL_BACK_TO_BODY' as const,
      confidence: 'deterministic' as const,
      summary: 'Focus fell back to body.',
    };

    const [group] = groupRuntimeInteractions([
      event({
        id: '1',
        timestamp: 10,
        kind: 'focus-lost',
        title: 'Focus lost',
        interactionId: 'ix-a-1',
        causes: [rootCause],
      }),
      event({
        id: '2',
        timestamp: 11,
        kind: 'focus-lost',
        title: 'Focus lost again',
        interactionId: 'ix-a-1',
        causes: [rootCause],
      }),
    ]);

    expect(group?.causes).toEqual([rootCause]);
  });

  it('builds a useful interaction title from the user action', () => {
    const [group] = groupRuntimeInteractions([
      event({
        id: '1',
        timestamp: 10,
        kind: 'keydown',
        title: 'Key: Enter',
        interactionId: 'ix-a-1',
        element: { tag: 'button', selector: '#save', name: 'Save profile' },
      }),
    ]);

    expect(group && runtimeInteractionTitle(group)).toBe('Key: Enter · Save profile');
  });
});
