export const HTML_OBSOLETE_SNAPSHOT_DATE = '2026-08-28';
export const HTML_OBSOLETE_REFERENCE_URL = 'https://html.spec.whatwg.org/multipage/obsolete.html';

export interface ObsoleteElementDefinition {
  tag: string;
  replacement: string;
}

export interface ObsoleteAttributeDefinition {
  attribute: string;
  elements: readonly string[] | '*';
  replacement: string;
}

export const OBSOLETE_ELEMENTS: readonly ObsoleteElementDefinition[] = [
  { tag: 'applet', replacement: 'Use <embed> or <object> instead.' },
  { tag: 'acronym', replacement: 'Use <abbr> instead.' },
  { tag: 'bgsound', replacement: 'Use <audio> instead.' },
  { tag: 'dir', replacement: 'Use <ul> instead.' },
  { tag: 'frame', replacement: 'Use <iframe> and CSS, or generate complete pages server-side.' },
  { tag: 'frameset', replacement: 'Use <iframe> and CSS, or generate complete pages server-side.' },
  { tag: 'noframes', replacement: 'Use <iframe> and CSS, or generate complete pages server-side.' },
  { tag: 'isindex', replacement: 'Use an explicit <form> and text control.' },
  { tag: 'keygen', replacement: 'Use native device management or the Web Cryptography API, depending on the use case.' },
  { tag: 'listing', replacement: 'Use <pre> and <code> instead.' },
  { tag: 'menuitem', replacement: 'Use script and the contextmenu event for custom context menus.' },
  { tag: 'nextid', replacement: 'Use modern unique identifiers instead.' },
  { tag: 'noembed', replacement: 'Use <object> when fallback content is required.' },
  { tag: 'param', replacement: 'Use the data attribute on <object> to identify the external resource.' },
  { tag: 'plaintext', replacement: 'Serve plain text with the text/plain MIME type instead.' },
  { tag: 'rb', replacement: 'Provide ruby base content directly inside <ruby> or use nested <ruby> elements.' },
  { tag: 'rtc', replacement: 'Use current <ruby> structure instead.' },
  { tag: 'strike', replacement: 'Use <del> for edits or <s> when the content is no longer accurate/relevant.' },
  { tag: 'xmp', replacement: 'Use <pre> and <code>, escaping < and & as needed.' },
  { tag: 'basefont', replacement: 'Use CSS instead.' },
  { tag: 'big', replacement: 'Use semantic text elements where appropriate, or CSS for presentation.' },
  { tag: 'blink', replacement: 'Use appropriate semantic HTML and CSS instead.' },
  { tag: 'center', replacement: 'Use CSS for alignment instead.' },
  { tag: 'font', replacement: 'Use CSS for typography and color instead.' },
  { tag: 'marquee', replacement: 'Use CSS animations/transitions where motion is appropriate.' },
  { tag: 'multicol', replacement: 'Use CSS multi-column layout instead.' },
  { tag: 'nobr', replacement: 'Use CSS white-space behavior instead.' },
  { tag: 'spacer', replacement: 'Use CSS spacing/layout instead.' },
  { tag: 'tt', replacement: 'Use <kbd>, <var>, <code>, <samp>, another semantic element, or CSS according to meaning.' },
] as const;

const DATA_SRC_ELEMENTS = ['a', 'button', 'div', 'frame', 'iframe', 'img', 'input', 'label', 'legend', 'marquee', 'object', 'option', 'select', 'span', 'table', 'textarea'] as const;
const DATA_FLD_ELEMENTS = ['a', 'button', 'div', 'fieldset', 'frame', 'iframe', 'img', 'input', 'label', 'legend', 'marquee', 'object', 'select', 'span', 'textarea'] as const;
const DATA_FORMAT_AS_ELEMENTS = ['button', 'div', 'input', 'label', 'legend', 'marquee', 'object', 'option', 'select', 'span', 'table'] as const;
const TABLE_SECTION_ELEMENTS = ['tbody', 'thead', 'tfoot'] as const;
const TABLE_CELL_ELEMENTS = ['td', 'th'] as const;
const BACKGROUND_ELEMENTS = ['body', 'table', 'thead', 'tbody', 'tfoot', 'tr', 'td', 'th'] as const;

/**
 * Non-conforming obsolete attributes from HTML Living Standard §16.2.
 * Special conditional cases (img[border], script[charset/language], style[type],
 * a[name]) are evaluated separately because some values remain obsolete-but-conforming.
 */
export const OBSOLETE_ATTRIBUTES: readonly ObsoleteAttributeDefinition[] = [
  { attribute: 'charset', elements: ['a', 'link'], replacement: 'Use the linked resource Content-Type instead.' },
  { attribute: 'coords', elements: ['a'], replacement: 'Use <area> for image-map regions.' },
  { attribute: 'shape', elements: ['a'], replacement: 'Use <area> for image-map regions.' },
  { attribute: 'methods', elements: ['a', 'link'], replacement: 'Use HTTP OPTIONS where applicable.' },
  { attribute: 'name', elements: ['embed', 'img', 'option'], replacement: 'Use id instead.' },
  { attribute: 'rev', elements: ['a', 'link'], replacement: 'Use rel with the opposite relationship term.' },
  { attribute: 'urn', elements: ['a', 'link'], replacement: 'Use href for the preferred persistent identifier.' },
  { attribute: 'accept', elements: ['form'], replacement: 'Use accept on the relevant <input> elements.' },
  { attribute: 'hreflang', elements: ['area'], replacement: 'Omit this ineffective attribute.' },
  { attribute: 'type', elements: ['area'], replacement: 'Omit this ineffective attribute.' },
  { attribute: 'nohref', elements: ['area'], replacement: 'Omit href instead.' },
  { attribute: 'profile', elements: ['head'], replacement: 'Omit the attribute.' },
  { attribute: 'manifest', elements: ['html'], replacement: 'Use service workers instead.' },
  { attribute: 'version', elements: ['html'], replacement: 'Omit the attribute.' },
  { attribute: 'ismap', elements: ['input'], replacement: 'Omit the attribute.' },
  { attribute: 'usemap', elements: ['input', 'object'], replacement: 'Use <img> for image maps.' },
  { attribute: 'longdesc', elements: ['iframe', 'img'], replacement: 'Use a normal link to the long description.' },
  { attribute: 'lowsrc', elements: ['img'], replacement: 'Use a single progressively encoded image when appropriate.' },
  { attribute: 'target', elements: ['link'], replacement: 'Omit the attribute.' },
  { attribute: 'type', elements: ['menu'], replacement: 'Use script for custom context menus; omit it for toolbar menus.' },
  { attribute: 'label', elements: ['menu'], replacement: 'Use script and current menu patterns instead.' },
  { attribute: 'contextmenu', elements: '*', replacement: 'Use script and the contextmenu event.' },
  { attribute: 'onshow', elements: '*', replacement: 'Use script and the contextmenu event.' },
  { attribute: 'scheme', elements: ['meta'], replacement: 'Encode the scheme in the value where necessary.' },
  { attribute: 'archive', elements: ['object'], replacement: 'Use data and type on <object>.' },
  { attribute: 'classid', elements: ['object'], replacement: 'Use data and type on <object>.' },
  { attribute: 'code', elements: ['object'], replacement: 'Use data and type on <object>.' },
  { attribute: 'codebase', elements: ['object'], replacement: 'Use data and type on <object>.' },
  { attribute: 'codetype', elements: ['object'], replacement: 'Use data and type on <object>.' },
  { attribute: 'declare', elements: ['object'], replacement: 'Repeat the <object> element when the resource is reused.' },
  { attribute: 'standby', elements: ['object'], replacement: 'Optimize the resource rather than providing standby text.' },
  { attribute: 'typemustmatch', elements: ['object'], replacement: 'Avoid <object> with untrusted resources.' },
  { attribute: 'event', elements: ['script'], replacement: 'Use DOM event listeners.' },
  { attribute: 'for', elements: ['script'], replacement: 'Use DOM event listeners.' },
  { attribute: 'datapagesize', elements: ['table'], replacement: 'Omit the attribute.' },
  { attribute: 'summary', elements: ['table'], replacement: 'Describe the table using current table markup and surrounding content.' },
  { attribute: 'abbr', elements: ['td'], replacement: 'Use concise cell text/title, or <th abbr> when it is a header cell.' },
  { attribute: 'axis', elements: TABLE_CELL_ELEMENTS, replacement: 'Use scope on the relevant <th>.' },
  { attribute: 'scope', elements: ['td'], replacement: 'Use <th> for heading cells.' },
  { attribute: 'datasrc', elements: DATA_SRC_ELEMENTS, replacement: 'Use script and current data-fetching APIs.' },
  { attribute: 'datafld', elements: DATA_FLD_ELEMENTS, replacement: 'Use script and current data-binding/fetching APIs.' },
  { attribute: 'dataformatas', elements: DATA_FORMAT_AS_ELEMENTS, replacement: 'Use script and current rendering/data APIs.' },
  { attribute: 'dropzone', elements: '*', replacement: 'Handle dragenter/dragover with script.' },
  { attribute: 'alink', elements: ['body'], replacement: 'Use CSS instead.' },
  { attribute: 'bgcolor', elements: ['body'], replacement: 'Use CSS instead.' },
  { attribute: 'bottommargin', elements: ['body'], replacement: 'Use CSS instead.' },
  { attribute: 'leftmargin', elements: ['body'], replacement: 'Use CSS instead.' },
  { attribute: 'link', elements: ['body'], replacement: 'Use CSS instead.' },
  { attribute: 'marginheight', elements: ['body'], replacement: 'Use CSS instead.' },
  { attribute: 'marginwidth', elements: ['body'], replacement: 'Use CSS instead.' },
  { attribute: 'rightmargin', elements: ['body'], replacement: 'Use CSS instead.' },
  { attribute: 'text', elements: ['body'], replacement: 'Use CSS instead.' },
  { attribute: 'topmargin', elements: ['body'], replacement: 'Use CSS instead.' },
  { attribute: 'vlink', elements: ['body'], replacement: 'Use CSS instead.' },
  { attribute: 'clear', elements: ['br'], replacement: 'Use CSS instead.' },
  { attribute: 'align', elements: ['caption'], replacement: 'Use CSS instead.' },
  { attribute: 'align', elements: ['col'], replacement: 'Use CSS instead.' },
  { attribute: 'char', elements: ['col'], replacement: 'Use CSS instead.' },
  { attribute: 'charoff', elements: ['col'], replacement: 'Use CSS instead.' },
  { attribute: 'valign', elements: ['col'], replacement: 'Use CSS instead.' },
  { attribute: 'width', elements: ['col'], replacement: 'Use CSS instead.' },
  { attribute: 'align', elements: ['div'], replacement: 'Use CSS instead.' },
  { attribute: 'compact', elements: ['dl'], replacement: 'Use CSS instead.' },
  { attribute: 'align', elements: ['embed'], replacement: 'Use CSS instead.' },
  { attribute: 'hspace', elements: ['embed'], replacement: 'Use CSS instead.' },
  { attribute: 'vspace', elements: ['embed'], replacement: 'Use CSS instead.' },
  { attribute: 'align', elements: ['hr'], replacement: 'Use CSS instead.' },
  { attribute: 'color', elements: ['hr'], replacement: 'Use CSS instead.' },
  { attribute: 'noshade', elements: ['hr'], replacement: 'Use CSS instead.' },
  { attribute: 'size', elements: ['hr'], replacement: 'Use CSS instead.' },
  { attribute: 'width', elements: ['hr'], replacement: 'Use CSS instead.' },
  { attribute: 'align', elements: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'], replacement: 'Use CSS instead.' },
  { attribute: 'align', elements: ['iframe'], replacement: 'Use CSS instead.' },
  { attribute: 'allowtransparency', elements: ['iframe'], replacement: 'Use current iframe/CSS behavior instead.' },
  { attribute: 'frameborder', elements: ['iframe'], replacement: 'Use CSS border instead.' },
  { attribute: 'framespacing', elements: ['iframe'], replacement: 'Use CSS instead.' },
  { attribute: 'hspace', elements: ['iframe'], replacement: 'Use CSS instead.' },
  { attribute: 'marginheight', elements: ['iframe'], replacement: 'Use CSS instead.' },
  { attribute: 'marginwidth', elements: ['iframe'], replacement: 'Use CSS instead.' },
  { attribute: 'scrolling', elements: ['iframe'], replacement: 'Use current iframe scrolling behavior/CSS instead.' },
  { attribute: 'vspace', elements: ['iframe'], replacement: 'Use CSS instead.' },
  { attribute: 'align', elements: ['input'], replacement: 'Use CSS instead.' },
  { attribute: 'border', elements: ['input'], replacement: 'Use CSS instead.' },
  { attribute: 'hspace', elements: ['input'], replacement: 'Use CSS instead.' },
  { attribute: 'vspace', elements: ['input'], replacement: 'Use CSS instead.' },
  { attribute: 'align', elements: ['img'], replacement: 'Use CSS instead.' },
  { attribute: 'hspace', elements: ['img'], replacement: 'Use CSS instead.' },
  { attribute: 'vspace', elements: ['img'], replacement: 'Use CSS instead.' },
  { attribute: 'align', elements: ['legend'], replacement: 'Use CSS instead.' },
  { attribute: 'type', elements: ['li'], replacement: 'Use CSS/list semantics instead.' },
  { attribute: 'compact', elements: ['menu'], replacement: 'Use CSS instead.' },
  { attribute: 'align', elements: ['object'], replacement: 'Use CSS instead.' },
  { attribute: 'border', elements: ['object'], replacement: 'Use CSS instead.' },
  { attribute: 'hspace', elements: ['object'], replacement: 'Use CSS instead.' },
  { attribute: 'vspace', elements: ['object'], replacement: 'Use CSS instead.' },
  { attribute: 'compact', elements: ['ol'], replacement: 'Use CSS instead.' },
  { attribute: 'align', elements: ['p'], replacement: 'Use CSS instead.' },
  { attribute: 'width', elements: ['pre'], replacement: 'Use CSS instead.' },
  { attribute: 'align', elements: ['table'], replacement: 'Use CSS instead.' },
  { attribute: 'bgcolor', elements: ['table'], replacement: 'Use CSS instead.' },
  { attribute: 'border', elements: ['table'], replacement: 'Use CSS instead.' },
  { attribute: 'bordercolor', elements: ['table'], replacement: 'Use CSS instead.' },
  { attribute: 'cellpadding', elements: ['table'], replacement: 'Use CSS instead.' },
  { attribute: 'cellspacing', elements: ['table'], replacement: 'Use CSS instead.' },
  { attribute: 'frame', elements: ['table'], replacement: 'Use CSS instead.' },
  { attribute: 'height', elements: ['table'], replacement: 'Use CSS instead.' },
  { attribute: 'rules', elements: ['table'], replacement: 'Use CSS instead.' },
  { attribute: 'width', elements: ['table'], replacement: 'Use CSS instead.' },
  { attribute: 'align', elements: TABLE_SECTION_ELEMENTS, replacement: 'Use CSS instead.' },
  { attribute: 'char', elements: TABLE_SECTION_ELEMENTS, replacement: 'Use CSS instead.' },
  { attribute: 'charoff', elements: TABLE_SECTION_ELEMENTS, replacement: 'Use CSS instead.' },
  { attribute: 'height', elements: TABLE_SECTION_ELEMENTS, replacement: 'Use CSS instead.' },
  { attribute: 'valign', elements: TABLE_SECTION_ELEMENTS, replacement: 'Use CSS instead.' },
  { attribute: 'align', elements: TABLE_CELL_ELEMENTS, replacement: 'Use CSS instead.' },
  { attribute: 'bgcolor', elements: TABLE_CELL_ELEMENTS, replacement: 'Use CSS instead.' },
  { attribute: 'char', elements: TABLE_CELL_ELEMENTS, replacement: 'Use CSS instead.' },
  { attribute: 'charoff', elements: TABLE_CELL_ELEMENTS, replacement: 'Use CSS instead.' },
  { attribute: 'height', elements: TABLE_CELL_ELEMENTS, replacement: 'Use CSS instead.' },
  { attribute: 'nowrap', elements: TABLE_CELL_ELEMENTS, replacement: 'Use CSS white-space instead.' },
  { attribute: 'valign', elements: TABLE_CELL_ELEMENTS, replacement: 'Use CSS instead.' },
  { attribute: 'width', elements: TABLE_CELL_ELEMENTS, replacement: 'Use CSS instead.' },
  { attribute: 'align', elements: ['tr'], replacement: 'Use CSS instead.' },
  { attribute: 'bgcolor', elements: ['tr'], replacement: 'Use CSS instead.' },
  { attribute: 'char', elements: ['tr'], replacement: 'Use CSS instead.' },
  { attribute: 'charoff', elements: ['tr'], replacement: 'Use CSS instead.' },
  { attribute: 'height', elements: ['tr'], replacement: 'Use CSS instead.' },
  { attribute: 'valign', elements: ['tr'], replacement: 'Use CSS instead.' },
  { attribute: 'compact', elements: ['ul'], replacement: 'Use CSS instead.' },
  { attribute: 'type', elements: ['ul'], replacement: 'Use CSS/list-style instead.' },
  { attribute: 'background', elements: BACKGROUND_ELEMENTS, replacement: 'Use CSS background properties instead.' },
] as const;

export const JAVASCRIPT_MIME_TYPE_ESSENCES = new Set([
  'application/ecmascript',
  'application/javascript',
  'application/x-ecmascript',
  'application/x-javascript',
  'text/ecmascript',
  'text/javascript',
  'text/javascript1.0',
  'text/javascript1.1',
  'text/javascript1.2',
  'text/javascript1.3',
  'text/javascript1.4',
  'text/javascript1.5',
  'text/jscript',
  'text/livescript',
  'text/x-ecmascript',
  'text/x-javascript',
]);
